# Generated by Django 4.1.5 on 2023-09-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jk', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('nim', models.IntegerField()),
                ('prodi', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('nomor', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
