# Generated by Django 4.1.5 on 2023-09-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0002_sertifikat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bidang', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('nama_pengurus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='ITC_APP.anggota')),
            ],
        ),
    ]
