# Generated by Django 4.1.5 on 2023-09-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0003_bidang_pengurus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='bidang',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidang', to='ITC_APP.bidang'),
            preserve_default=False,
        ),
    ]
