# Generated by Django 4.1.5 on 2023-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0004_pengurus_bidang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
                ('jenis_program', models.CharField(max_length=255)),
                ('tglM_pelaksanaan', models.DateField()),
                ('tglS_pelaksanaan', models.DateField()),
                ('lokasi_program', models.CharField(max_length=255)),
                ('waktu', models.CharField(max_length=255)),
                ('keterangan', models.TextField()),
            ],
        ),
    ]
