# Generated by Django 4.1.5 on 2023-09-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0006_rename_tglm_pelaksanaan_program_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='diverifikasi',
            field=models.BooleanField(default=False),
        ),
    ]
