# Generated by Django 4.1.5 on 2023-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0007_anggota_diverifikasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='cetak',
            field=models.BooleanField(default=False),
        ),
    ]
