# Generated by Django 4.1.5 on 2023-09-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0008_anggota_cetak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='cetak',
        ),
    ]
