# Generated by Django 4.1.5 on 2023-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0009_remove_anggota_cetak'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='cetak',
            field=models.BooleanField(default=False),
        ),
    ]
