# Generated by Django 4.1.5 on 2023-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0010_anggota_cetak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
