# Generated by Django 4.1.5 on 2023-10-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nim',
            field=models.IntegerField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nomor',
            field=models.CharField(max_length=12),
        ),
    ]
