# Generated by Django 4.1.5 on 2023-10-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0013_alter_anggota_nim_alter_anggota_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nim',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
