# Generated by Django 4.1.5 on 2023-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITC_APP', '0014_alter_anggota_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='nomor',
            field=models.CharField(max_length=15),
        ),
    ]
